import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/shared/NavigationBar";
import Logo from "@/components/shared/Logo";
import { setupDatabase } from "@/lib/database";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HoardPress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ensure the database is setup
  setupDatabase();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-5 flex flex-col gap-5">
          <header className="wrapper flex items-center gap-5">
            <Logo />

            <NavigationBar />
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
